return {
	providers = {
		{
			name = "industrialforegoing:black_hole_unit_tile_201",
			content = "LZH",
		},
		{
			name = "industrialforegoing:black_hole_unit_tile_199",
			content = "AdvancedHeatExchanger",
		},
		{
			name = "industrialforegoing:black_hole_unit_tile_200",
			content = "NetherStarEnrichedQuad",
		},
	},
	reactor = {
		name = "ic2:reactor chamber_411",
		connectionSide = "up",
	},
	plan = {
		-- Row 1
		"LZH",
		"AdvancedHeatExchanger",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"AdvancedHeatExchanger",
		"LZH",
		-- Row 2
		"AdvancedHeatExchanger",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"AdvancedHeatExchanger",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"AdvancedHeatExchanger",
		-- Row 3
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		-- Row 4
		"NetherStarEnrichedQuad",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"AdvancedHeatExchanger",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"NetherStarEnrichedQuad",
		-- Row 5
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		-- Row 6
		"AdvancedHeatExchanger",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"AdvancedHeatExchanger",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"AdvancedHeatExchanger",
	},
}
