return {
	providerNames = {
		"industrialforegoing:black_hole_unit_tile_2",
		"industrialforegoing:black_hole_unit_tile_3",
		"industrialforegoing:black_hole_unit_tile_4",
	},
	reactorName = "ic2:reactor chamber_13",
	reactorConnectionSide = "up",
	plan = {
		-- Row 1
		"LZH",
		"AdvancedHeatExchanger",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"AdvancedHeatExchanger",
		"LZH",
		-- Row 2
		"AdvancedHeatExchanger",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"AdvancedHeatExchanger",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"AdvancedHeatExchanger",
		-- Row 3
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		-- Row 4
		"NetherStarEnrichedQuad",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"AdvancedHeatExchanger",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"NetherStarEnrichedQuad",
		-- Row 5
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		-- Row 6
		"AdvancedHeatExchanger",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"AdvancedHeatExchanger",
		"LZH",
		"NetherStarEnrichedQuad",
		"LZH",
		"AdvancedHeatExchanger",
	},
}
