local chamber = peripheral.wrap("back")
local reactor = chamber.getReactorCore()
local inv = reactor.list()
local invAsStr = textutils.serialize(inv)
--textutils.pagedPrint(invAsStr)
local itemMeta1 = reactor.getItemMeta(1)
textutils.pagedPrint(itemMeta1)
