local chamber = peripheral.wrap("back")
local reactor = chamber.getReactorCore()
local docs = reactor.getDocs()
local docString = textutils.serialize(docs)
local file = fs.open("core", "w")
file.write(docString)
file.close()
shell.run("pastebin put core")
