local chamber = peripheral.wrap("back")
local reactor = chamber.getReactorCore()
local inv = reactor.list()
local invAsStr = textutils.serialize(inv)
--textutils.pagedPrint(invAsStr)
local itemMeta1 = textutils.serialize(reactor.getItemMeta(1))
print(itemMeta1)
local itemMeta22 = textutils.serialize(reactor.getItemMeta(22))
print(itemMeta22)

print("Press any key to finish")
local event, key = os.pullEvent("key")
